/**
 * Live local business search via OpenStreetMap Overpass (no API key).
 * Real-time by lat/lng — not a hardcoded city dump.
 */

import type { PlaceDetails } from "./details";
import { loadVertical } from "@/lib/config/loadVertical";

const UA = "LeverageAI/1.0 (hackathon; contact: leverageai)";

/** Broader amenity sets so dense US metros return results. */
function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * OSM syntax is generated by trusted code; only validated tag/value data and
 * escaped name terms come from vertical JSON. This is config-driven without
 * allowing a config file to inject arbitrary Overpass statements.
 */
function overpassBody(
  vertical: string,
  lat: number,
  lng: number,
  radiusM: number,
): string {
  const config = loadVertical(vertical);
  const tagQueries = config.provider_osm.tags.map(({ key, value }) =>
    value
      ? `  nwr["${key}"="${value}"](around:${radiusM},${lat},${lng});`
      : `  nwr["${key}"](around:${radiusM},${lat},${lng});`,
  );
  const namePattern = config.provider_osm.name_terms
    .map(escapeRegex)
    .join("|");

  return `
[out:json][timeout:28];
(
${tagQueries.join("\n")}
  nwr["name"~"${namePattern}",i](around:${radiusM},${lat},${lng});
);
out center 25;
`;
}

export async function searchOverpassNear(
  vertical: string,
  lat: number,
  lng: number,
  radiusM = 25000
): Promise<PlaceDetails[]> {
  const endpoints = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
  ];
  const body = overpassBody(vertical, lat, lng, radiusM);

  const results = await Promise.all(
    endpoints.map(async (endpoint): Promise<PlaceDetails[]> => {
    try {
      const res = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          "User-Agent": UA,
        },
        body: `data=${encodeURIComponent(body)}`,
        signal: AbortSignal.timeout(3_500),
      });
      if (!res.ok) {
        console.warn("[overpass] http", endpoint, res.status);
        return [];
      }
      const data = (await res.json()) as {
        elements?: Array<{
          id: number;
          type: string;
          lat?: number;
          lon?: number;
          center?: { lat: number; lon: number };
          tags?: Record<string, string>;
        }>;
      };

      const seen = new Set<string>();
      const out: PlaceDetails[] = [];
      for (const el of data.elements || []) {
        const tags = el.tags || {};
        const name = tags.name || tags.brand || tags.operator;
        if (!name) continue;
        const key = name.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        const plat = el.lat ?? el.center?.lat;
        const plng = el.lon ?? el.center?.lon;
        const phone = tags.phone || tags["contact:phone"];
        const website = tags.website || tags["contact:website"];
        const street = [tags["addr:housenumber"], tags["addr:street"]]
          .filter(Boolean)
          .join(" ");
        const addr = [street, tags["addr:city"], tags["addr:postcode"]]
          .filter(Boolean)
          .join(", ");
        out.push({
          place_id: `osm-${el.type}-${el.id}`,
          displayName: name,
          nationalPhoneNumber: phone,
          formattedAddress: addr || undefined,
          websiteUri: website,
          googleMapsUri:
            plat != null && plng != null
              ? `https://www.openstreetmap.org/?mlat=${plat}&mlon=${plng}#map=16/${plat}/${plng}`
              : undefined,
          location:
            plat != null && plng != null
              ? { lat: plat, lng: plng }
              : undefined,
          businessStatus: "OPERATIONAL",
          reviews: [],
          fetched_at: new Date().toISOString(),
          source: "OpenStreetMap Overpass (live)",
        });
        if (out.length >= 12) break;
      }
      return out;
    } catch (e) {
      console.warn("[overpass] fail", endpoint, e);
      return [];
    }
    }),
  );
  return results.find((result) => result.length > 0) || [];
}
