/**
 * Live local business search via OpenStreetMap Overpass (no API key).
 * Real-time by lat/lng — not a hardcoded city dump.
 */

import type { PlaceDetails } from "./details";
import { loadVertical } from "@/lib/config/loadVertical";

const DEFAULT_OVERPASS_URL = "https://overpass-api.de/api/interpreter";
const DEFAULT_QLEVER_URL = "https://qlever.dev/api/osm-planet";
const DEFAULT_UA =
  "LeverageAI/1.0 (contact: https://leverageai-tawny.vercel.app)";

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function escapeSparql(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function pointFromWkt(value: string): { lat: number; lng: number } | null {
  const match = value.match(/^POINT\((-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\)$/i);
  if (!match) return null;
  const lng = Number(match[1]);
  const lat = Number(match[2]);
  return Number.isFinite(lat) && Number.isFinite(lng) ? { lat, lng } : null;
}

async function searchQLeverNear(
  vertical: string,
  lat: number,
  lng: number,
  radiusM: number,
): Promise<PlaceDetails[]> {
  const config = loadVertical(vertical);
  const namePattern = config.provider_osm.name_terms
    .map(escapeRegex)
    .join("|");
  const branches = config.provider_osm.tags.map(({ key, value, name_match }) => {
    const object = value ? `"${escapeSparql(value)}"` : "?tagValue";
    const filter = name_match
      ? ` ?element osmkey:name ?matchedName . FILTER(REGEX(STR(?matchedName), "${escapeSparql(namePattern)}", "i"))`
      : "";
    return `{ ?element osmkey:${key} ${object} .${filter} }`;
  });
  const query = `
PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
PREFIX osm: <https://www.openstreetmap.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
SELECT DISTINCT ?element ?name ?geometry ?phone ?contactPhone ?website ?contactWebsite ?houseNumber ?street ?city ?postcode WHERE {
  ${branches.join(" UNION ")}
  ?element a osm:node ; osmkey:name ?name ; geo:hasGeometry/geo:asWKT ?geometry .
  BIND("POINT(${lng} ${lat})"^^geo:wktLiteral AS ?center)
  FILTER(geof:distance(?geometry, ?center) <= ${Math.max(1, Math.round(radiusM / 1000))})
  OPTIONAL { ?element osmkey:phone ?phone . }
  OPTIONAL { ?element osmkey:contact:phone ?contactPhone . }
  OPTIONAL { ?element osmkey:website ?website . }
  OPTIONAL { ?element osmkey:contact:website ?contactWebsite . }
  OPTIONAL { ?element osmkey:addr:housenumber ?houseNumber . }
  OPTIONAL { ?element osmkey:addr:street ?street . }
  OPTIONAL { ?element osmkey:addr:city ?city . }
  OPTIONAL { ?element osmkey:addr:postcode ?postcode . }
} LIMIT 25`;
  try {
    const res = await fetch(
      process.env.OSM_QLEVER_URL?.trim() || DEFAULT_QLEVER_URL,
      {
        method: "POST",
        headers: {
          Accept: "application/sparql-results+json",
          "Content-Type": "application/x-www-form-urlencoded",
          "User-Agent": process.env.OSM_USER_AGENT?.trim() || DEFAULT_UA,
        },
        body: `query=${encodeURIComponent(query)}`,
        signal: AbortSignal.timeout(15_000),
      },
    );
    if (!res.ok) return [];
    const data = (await res.json()) as {
      results?: { bindings?: Array<Record<string, { value?: string }>> };
    };
    return (data.results?.bindings || []).flatMap((row, index) => {
      const point = pointFromWkt(row.geometry?.value || "");
      const name = row.name?.value?.trim();
      if (!point || !name) return [];
      const element = row.element?.value || `qlever-${index}`;
      const address = [
        [row.houseNumber?.value, row.street?.value].filter(Boolean).join(" "),
        row.city?.value,
        row.postcode?.value,
      ].filter(Boolean).join(", ");
      return [{
        place_id: `osm-${element.split("/").slice(-2).join("-")}`,
        displayName: name,
        nationalPhoneNumber: row.phone?.value || row.contactPhone?.value,
        formattedAddress: address || undefined,
        websiteUri: row.website?.value || row.contactWebsite?.value,
        googleMapsUri: element.startsWith("https://www.openstreetmap.org/")
          ? element
          : `https://www.openstreetmap.org/?mlat=${point.lat}&mlon=${point.lng}`,
        location: point,
        businessStatus: "OPERATIONAL",
        reviews: [],
        fetched_at: new Date().toISOString(),
        source: "OpenStreetMap QLever (live)",
      } satisfies PlaceDetails];
    });
  } catch (error) {
    console.warn("[qlever] fail", error);
    return [];
  }
}

/**
 * OSM syntax is generated by trusted code; only validated tag/value data and
 * values come from vertical JSON. Precise tags keep public Overpass queries
 * small and avoid expensive city-wide regular-expression scans.
 */
function overpassBody(
  vertical: string,
  lat: number,
  lng: number,
  radiusM: number,
): string {
  const config = loadVertical(vertical);
  const namePattern = config.provider_osm.name_terms
    .map(escapeRegex)
    .join("|");
  const tagQueries = config.provider_osm.tags.map(
    ({ key, value, name_match }) => {
      const tag = value ? `["${key}"="${value}"]` : `["${key}"]`;
      const name = name_match ? `["name"~"${namePattern}",i]` : "";
      return `  nwr${tag}${name}(around:${radiusM},${lat},${lng});`;
    },
  );
  return `
[out:json][timeout:15];
(
${tagQueries.join("\n")}
);
out center 25;
`;
}

export async function searchOverpassNear(
  vertical: string,
  lat: number,
  lng: number,
  radiusM = 25000
): Promise<PlaceDetails[]> {
  const endpoints = [
    process.env.OSM_OVERPASS_URL?.trim() || DEFAULT_OVERPASS_URL,
  ];
  const body = overpassBody(vertical, lat, lng, radiusM);

  // Public Overpass guidance asks clients to avoid parallel requests from one
  // host. Try configured endpoints sequentially and return the first result.
  for (const endpoint of endpoints) {
    try {
      const res = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          "User-Agent": process.env.OSM_USER_AGENT?.trim() || DEFAULT_UA,
        },
        body: `data=${encodeURIComponent(body)}`,
        signal: AbortSignal.timeout(20_000),
      });
      if (!res.ok) {
        console.warn("[overpass] http", endpoint, res.status);
        return [];
      }
      const data = (await res.json()) as {
        elements?: Array<{
          id: number;
          type: string;
          lat?: number;
          lon?: number;
          center?: { lat: number; lon: number };
          tags?: Record<string, string>;
        }>;
      };

      const seen = new Set<string>();
      const out: PlaceDetails[] = [];
      for (const el of data.elements || []) {
        const tags = el.tags || {};
        const name = tags.name || tags.brand || tags.operator;
        if (!name) continue;
        const key = name.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        const plat = el.lat ?? el.center?.lat;
        const plng = el.lon ?? el.center?.lon;
        const phone = tags.phone || tags["contact:phone"];
        const website = tags.website || tags["contact:website"];
        const street = [tags["addr:housenumber"], tags["addr:street"]]
          .filter(Boolean)
          .join(" ");
        const addr = [street, tags["addr:city"], tags["addr:postcode"]]
          .filter(Boolean)
          .join(", ");
        out.push({
          place_id: `osm-${el.type}-${el.id}`,
          displayName: name,
          nationalPhoneNumber: phone,
          formattedAddress: addr || undefined,
          websiteUri: website,
          googleMapsUri:
            plat != null && plng != null
              ? `https://www.openstreetmap.org/?mlat=${plat}&mlon=${plng}#map=16/${plat}/${plng}`
              : undefined,
          location:
            plat != null && plng != null
              ? { lat: plat, lng: plng }
              : undefined,
          businessStatus: "OPERATIONAL",
          reviews: [],
          fetched_at: new Date().toISOString(),
          source: "OpenStreetMap Overpass (live)",
        });
        if (out.length >= 12) break;
      }
      if (out.length > 0) return out;
    } catch (e) {
      console.warn("[overpass] fail", endpoint, e);
    }
  }
  return searchQLeverNear(vertical, lat, lng, radiusM);
}
